# 모든 프로파일에서 공통적으로 적용되어야 하는 사항

servers:
  - dev.bar.com
  - foo.bar.com
kdt:
  version: "default-v0.9"
  minimum-order-amount: 10
  support-vendors:
    -default
  description: |-
    dLine is default
    it is defualt setting
    without profiles

#logging:
#  level:
#    root: warn