# 프로파일1

spring.config.activate.on-profile: local

kdt:
  version: "v1.0"
  minimum-order-amount: 1
  support-vendors:
    - a
    - b
    - c
    - d
  description: |- # |는 그냥 여러 줄 표현, |-는 빈 줄 포함하지 않음을 표현
    line 1 Hello World!
    line 2 xxxx
    line 3 ...

